name: Build

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: curl https://github.com/jgm/pandoc/releases/download/2.9.2/pandoc-2.9.2-1-amd64.deb -s -L --output pandoc.deb && sudo dpkg -i pandoc.deb && sudo apt install -y texlive texlive-xetex
      - run: ./build.sh
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: build
      - uses: actions/deploy-to-dropbox@v1.0.4
        with: 
          DROPBOX_ACCESS_TOKEN: "${{ secrets.DROPBOX_ACCESS_TOKEN }}"
          GLOB: "/build/**/*"
          DROPBOX_DESTINATION_PATH_PREFIX: "/"
          DEBUG: true
